# Site settings
title: NEBE
email: contacto@nebe.org
description: "NEBE es un proyecto desarrollado por el ISS e Hivos de Holanda, Lidema de Bolivia y la Universidad San Francisco de Quito de Ecuador que se propone de estudiar los impactos de la nacionalización sobre los conflictos y la cooperación alrededor de las actividades extractivas en Bolivia y Ecuador."
baseurl: "//ciudadanointeligente.github.io/nebe" # the subpath of your site, e.g. /blog/
url: "//proyecto-nebe.org" # the base hostname & protocol for your site
twitter_username: "@proyectonebe"
bootstrap_version: "3.3.2"
jquery_version: "2.1.3"
google_analytics: "UA-60671039-1"

# Build settings
markdown: kramdown

# main page
header_txt: "LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT, SED DO EIUSMOD TEMPOR."
header_slide_1: "/img/home01.jpg"
header_slide_2: "/img/home02.jpg"
header_slide_3: "/img/home04.jpg"

#mapbox
mapbox-map: 'jgarrido.m42eof6c'
mapbox-token: 'pk.eyJ1IjoiamdhcnJpZG8iLCJhIjoiOVhrQ2ZwMCJ9.eItLrt9DzG1YNCbNZ0hhDg'

#reports
reports-zoom: 8
reports-lat: '-2.234'
reports-lng: '-77,656'

#collections
collections:
  reports:
    output: true
  investigations:
    output: true