# site settings
title: NEBE
email: 'contacto@nebe.org'
description: 'NEBE es un proyecto desarrollado por el ISS e Hivos de Holanda, Lidema de Bolivia y la Universidad San Francisco de Quito de Ecuador que se propone de estudiar los impactos de la nacionalización sobre los conflictos y la cooperación alrededor de las actividades extractivas en Bolivia y Ecuador.'
baseurl: '//nebe.ciudadanoi.org' #the subpath of your site, e.g. /blog/
url: '//nebe.ciudadanoi.org' #the base hostname & protocol for your site
twitter_username: '@proyectonebe'
bootstrap_version: '3.3.2'
jquery_version: '2.1.3'
google_analytics: 'UA-60671039-1'

# build settings
markdown: kramdown

# main page
header:
  txt: 'Proyecto NEBE'
  slide: ['/img/home01.jpg','/img/home02.jpg','//i.imgur.com/jXh99iH.jpg']

# reports
reportes:
  zoom: 3
  lat: '-2.234'
  lng: '-77,656'

# documents
dokuments:
  image: '/img/home02.jpg'
press:
  image: '//farm8.staticflickr.com/7441/12142574495_2741fd4e92_o.jpg'
news:
  image: '//farm4.staticflickr.com/3831/12127101124_f361434c19_o.jpg'
blog:
  image: '//farm3.staticflickr.com/2894/12142944844_2a13eb2bbc_o.jpg'
chronology:
  image: '//farm4.staticflickr.com/3804/12142826193_328a7520ce_o.jpg'

# mapbox
mapbox:
  map: 'jgarrido.m42eof6c'
  token: 'pk.eyJ1IjoiamdhcnJpZG8iLCJhIjoiOVhrQ2ZwMCJ9.eItLrt9DzG1YNCbNZ0hhDg'

# collections
collections:
  reports:
    output: true
  investigations:
    output: true
  comunities:
    output: true
  chronologies:
    output: true
  news:
    output: true
