# site settings
title: ARKAK SACHA
email: 'contacto@nebe.org'
description: 'NEBE es un proyecto desarrollado por el ISS e Hivos de Holanda, Lidema de Bolivia y la Universidad San Francisco de Quito de Ecuador que se propone de estudiar los impactos de la nacionalización sobre los conflictos y la cooperación alrededor de las actividades extractivas en Bolivia y Ecuador.'
baseurl: '//arkaksacha.org' #the subpath of your site, e.g. /blog/
url: '//arkaksacha.org' #the base hostname & protocol for your site
twitter_username: '@proyectonebe'
bootstrap_version: '3.3.2'
jquery_version: '2.1.3'
google_analytics: 'UA-60671039-1'

# build settings
markdown: kramdown

#pagination
itemsPerPage: 5

# main page
header:
  txt: 'ARKAK SACHA'
  welcome: '¡Bienvenidos a ARKAK SACHA (Protector del Bosque)! Esta plataforma busca ser una herramienta que integre experiencias, herramientas e información útil para el trabajo que las comunidades hacen en términos de monitoreo socio ambiental en relación con las industrias extractivas. Para ello, difundimos los hallazgos de los estudios realizados en el marco del proyecto NEBE y los reportes de las propias comunidades, así como noticias y opiniones relacionadas con los conflictos entre comunidades y extractivismo.'# '<p>¿Cómo nace NEBE? Desde el año 2011 el Instituto Internacional de Estudios Sociales de la Universidad Erasmus de Rotterdam (ISS/EUR) e HIVOS de Holanda, la Liga de Defensa del Medio Ambiente LIDEMA (Bolivia) y la Universidad San Francisco de Quito USFQ (Ecuador), a través del proyecto NEBE (Nacionalización de la Extracción en Bolivia y Ecuador) estudian los impactos, conflictos y cooperación que existen en torno a los recursos naturales en Bolivia y Ecuador. El proyecto cuenta con el apoyo de la Organización Holandesa de Investigación Científica - Programa de Investigación “Ciencia por el Desarrollo Global” (NWO/WOTRO) a través de un sub programa de conocimiento, investigación e innovación sobre el tema de Conflicto y Cooperación sobre Recursos Naturales en países en desarrollo [CoCooN por sus siglas en inglés). A partir del año 2014 se incorpora Perú en el proyecto y se amplían las áreas de investigación y acción.</p><p>Esperamos que ARKAK SACHA sea el lugar donde ustedes encuentren herramientas y apoyo para el fortalecimiento de los sistemas de monitoreo socio ambiental indígena, así como la defensa e incidencia que las organizaciones realizan a nivel nacional, regional y global. No duden en contactarnos con sus preguntas o sugerencias.<p>'
  slide: ['/img/home01.jpg','/img/home02.jpg','//i.imgur.com/jXh99iH.jpg']

# reports
reportes:
  zoom: 3
  lat: '-2.234'
  lng: '-77,656'

# documents
dokuments:
  image: '/img/home02.jpg'
press:
  image: '//farm8.staticflickr.com/7441/12142574495_2741fd4e92_o.jpg'
news_article:
  image: '//farm4.staticflickr.com/3831/12127101124_f361434c19_o.jpg'
blog:
  image: '//farm3.staticflickr.com/2894/12142944844_2a13eb2bbc_o.jpg'
chronology:
  image: '//farm4.staticflickr.com/3804/12142826193_328a7520ce_o.jpg'
resource:
  image: '//c2.staticflickr.com/2/1317/1076132657_5ea0371ac0_o.jpg' #https://www.flickr.com/photos/aragao/1076132657/

# mapbox
mapbox:
  map: 'jgarrido.m42eof6c'
  token: 'pk.eyJ1IjoiamdhcnJpZG8iLCJhIjoiOVhrQ2ZwMCJ9.eItLrt9DzG1YNCbNZ0hhDg'

# collections
collections:
  reports:
    output: true
  investigations:
    output: true
  communities:
    output: true
  chronologies:
    output: true
  news:
    output: true
  resources:
    output: true

# blog
disqus_shortname: 'arkak-sacha'

# newsletter
subscribe_form: '//docs.google.com/a/votainteligente.cl/forms/d/1HgaTV6PpTDVcGv12J8eCR1pylTQGcgnOnOfFY9VNdCQ/viewform'