# Site settings
title: NEBE
email: contacto@nebe.org
description: "NEBE es un proyecto desarrollado por el ISS e Hivos de Holanda, Lidema de Bolivia y la Universidad San Francisco de Quito de Ecuador que se propone de estudiar los impactos de la nacionalización sobre los conflictos y la cooperación alrededor de las actividades extractivas en Bolivia y Ecuador."
baseurl: "http://ciudadanointeligente.github.io/nebe/" # the subpath of your site, e.g. /blog/
url: "http://proyecto-nebe.org" # the base hostname & protocol for your site
twitter_username: "@proyectonebe"
bootstrap_version: "3.3.2"
jquery_version: "2.1.3"
fontawesome_version: "4.3.0"
angular_version: "1.3.15"
google_analytics: "UA-60671039-1"

# Build settings
markdown: kramdown

collections:
  experiences:
    output: true
  reports:
    output: true